# Generated by Django 5.2.5 on 2025-08-16 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tetris_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='title',
        ),
    ]
