# Generated by Django 5.2.5 on 2025-08-16 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tetris_api', '0003_rename_create_at_game_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='player',
            new_name='user',
        ),
    ]
