# Generated by Django 5.2.5 on 2025-08-16 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tetris_api', '0002_remove_game_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
